services:
  ticket-embedding-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ticket-embedding-api:0.2
    ports:
      - 8081:8000
    volumes:
      - /opt/projects/ticket-embedding-api/database:/opt/aiops/database
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]